[workspace]
channels = ["conda-forge"]
name = "pixi-for-VScode"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"
numpy = ">=2.4.2,<3"
pytorch = ">=2.10.0,<3"
pot = ">=0.9.6.post1,<0.10"
